<a href="https://colab.research.google.com/github/Leon-web-net/Learning_ML/blob/main/Feature_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn.datasets import fetch_openml

data = fetch_openml(name="titanic", version=1, as_frame=True)
type(data)

sklearn.utils._bunch.Bunch

In [ ]:
data["target"]

0       1
1       1
2       0
3       0
4       0
       ..
1304    0
1305    0
1306    0
1307    0
1308    0
Name: survived, Length: 1309, dtype: category
Categories (2, object): ['0', '1']

In [ ]:
df_y = pd.DataFrame(data.target)
df_X = pd.DataFrame(data.data)

df_X.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
df_y.head()

  survived
0        1
1        1
2        0
3        0
4        0

# Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

def LE_func(df, col):
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    return le

In [ ]:
le_dict= {}

In [ ]:

cols = ["sex", "embarked"]
for col in cols:
    if isinstance(df_X[col].dtype, pd.CategoricalDtype) or pd.api.types.is_object_dtype(df_X[col]):
      le_dict[col] = LE_func(df_X, col)
    else:
      print(f"{col} is of {df_X[col].dtype} and has not been labelEncoded")

df_X.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,"Allen, Miss. Elisabeth Walton",0,29.0000,0,0,24160,211.3375,B5,2,2,NaN,"St Louis, MO"
1,1,"Allison, Master. Hudson Trevor",1,0.9167,1,2,113781,151.5500,C22 C26,2,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,"Allison, Miss. Helen Loraine",0,2.0000,1,2,113781,151.5500,C22 C26,2,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,"Allison, Mr. Hudson Joshua Creighton",1,30.0000,1,2,113781,151.5500,C22 C26,2,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",0,25.0000,1,2,113781,151.5500,C22 C26,2,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
for col, le in le_dict.items():
    mapping = {label: idx for idx, label in enumerate(le.classes_)}
    print(f"{col}: {mapping}")

sex: {'female': 0, 'male': 1}
embarked: {'C': 0, 'Q': 1, 'S': 2, nan: 3}

# Ordinal Encoding

In [ ]:
from sklearn.datasets import fetch_openml

data = fetch_openml(name="credit-g", version=1, as_frame=True)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker
0,<0,6,critical/other existing credit,radio/tv,1169,no known savings,>=7,4,male single,none,4,real estate,67,none,own,2,skilled,1,yes,yes
1,0<=X<200,48,existing paid,radio/tv,5951,<100,1<=X<4,2,female div/dep/mar,none,2,real estate,22,none,own,1,skilled,1,none,yes
2,no checking,12,critical/other existing credit,education,2096,<100,4<=X<7,2,male single,none,3,real estate,49,none,own,1,unskilled resident,2,none,yes
3,<0,42,existing paid,furniture/equipment,7882,<100,4<=X<7,2,male single,guarantor,4,life insurance,45,none,for free,1,skilled,2,none,yes
4,<0,24,delayed previously,new car,4870,<100,1<=X<4,3,male single,none,4,no known property,53,none,for free,2,skilled,2,none,yes

In [ ]:
df_y = pd.DataFrame(data.target)
df_X = pd.DataFrame(data.data)

df_X.head()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker
0,<0,6,critical/other existing credit,radio/tv,1169,no known savings,>=7,4,male single,none,4,real estate,67,none,own,2,skilled,1,yes,yes
1,0<=X<200,48,existing paid,radio/tv,5951,<100,1<=X<4,2,female div/dep/mar,none,2,real estate,22,none,own,1,skilled,1,none,yes
2,no checking,12,critical/other existing credit,education,2096,<100,4<=X<7,2,male single,none,3,real estate,49,none,own,1,unskilled resident,2,none,yes
3,<0,42,existing paid,furniture/equipment,7882,<100,4<=X<7,2,male single,guarantor,4,life insurance,45,none,for free,1,skilled,2,none,yes
4,<0,24,delayed previously,new car,4870,<100,1<=X<4,3,male single,none,4,no known property,53,none,for free,2,skilled,2,none,yes

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

def OE_func(df, col,cats):
    oe = OrdinalEncoder(categories=[cats])
    df[col] = oe.fit_transform(df[[col]]).astype(int)
    return oe

In [ ]:
oe_dict = {}

In [ ]:
cols = ["checking_status", "credit_history"]
[df_X[col].unique() for col in cols]

[['<0', '0<=X<200', 'no checking', '>=200']
 Categories (4, object): ['0<=X<200', '<0', '>=200', 'no checking'],
 ['critical/other existing credit', 'existing paid', 'delayed previously', 'no credits/all paid', 'all paid']
 Categories (5, object): ['all paid', 'critical/other existing credit', 'delayed previously',
                          'existing paid', 'no credits/all paid']]

In [ ]:
category = {"checking_status": ['<0','no checking','0<=X<200','>=200'],
            "credit_history":['critical/other existing credit','delayed previously', 'existing paid', 'no credits/all paid', 'all paid']}
for col in cols:
    if isinstance(df_X[col].dtype, pd.CategoricalDtype) or pd.api.types.is_object_dtype(df_X[col]):
       oe_dict[col] = OE_func(df_X, col,category[col])
    else:
      print(f"{col} is of {df_X[col].dtype} and has not been labelEncoded")

df_X.head()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker
0,0,6,0,radio/tv,1169,no known savings,>=7,4,male single,none,4,real estate,67,none,own,2,skilled,1,yes,yes
1,2,48,2,radio/tv,5951,<100,1<=X<4,2,female div/dep/mar,none,2,real estate,22,none,own,1,skilled,1,none,yes
2,1,12,0,education,2096,<100,4<=X<7,2,male single,none,3,real estate,49,none,own,1,unskilled resident,2,none,yes
3,0,42,2,furniture/equipment,7882,<100,4<=X<7,2,male single,guarantor,4,life insurance,45,none,for free,1,skilled,2,none,yes
4,0,24,1,new car,4870,<100,1<=X<4,3,male single,none,4,no known property,53,none,for free,2,skilled,2,none,yes

In [ ]:
for col, oe in oe_dict.items():
    mapping = {label: idx for idx, label in enumerate(oe.categories_[0])}
    print(f"{col}: {mapping}")

checking_status: {'<0': 0, 'no checking': 1, '0<=X<200': 2, '>=200': 3}
credit_history: {'critical/other existing credit': 0, 'delayed previously': 1, 'existing paid': 2, 'no credits/all paid': 3, 'all paid': 4}

# One hot encoding

In [ ]:
import pandas as pd
from sklearn.datasets import fetch_openml

data = fetch_openml(name="titanic", version=1, as_frame=True)

In [ ]:
df_y = pd.DataFrame(data.target)
df_X = pd.DataFrame(data.data)

df_X.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
df_X = pd.get_dummies(df_X, columns=["sex", "embarked"], drop_first=True)
df_X.head()

,pclass,name,age,sibsp,parch,ticket,fare,cabin,boat,body,home.dest,sex_male,embarked_Q,embarked_S
0,1,"Allen, Miss. Elisabeth Walton",29.0000,0,0,24160,211.3375,B5,2,NaN,"St Louis, MO",False,False,True
1,1,"Allison, Master. Hudson Trevor",0.9167,1,2,113781,151.5500,C22 C26,11,NaN,"Montreal, PQ / Chesterville, ON",True,False,True
2,1,"Allison, Miss. Helen Loraine",2.0000,1,2,113781,151.5500,C22 C26,NaN,NaN,"Montreal, PQ / Chesterville, ON",False,False,True
3,1,"Allison, Mr. Hudson Joshua Creighton",30.0000,1,2,113781,151.5500,C22 C26,NaN,135.0,"Montreal, PQ / Chesterville, ON",True,False,True
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",25.0000,1,2,113781,151.5500,C22 C26,NaN,NaN,"Montreal, PQ / Chesterville, ON",False,False,True

# Binary Encoder